---
name: "ZUnit (native)"

on:
  push:
    branches: [next, main]
    paths:
      - ".github/workflows/test-native.yml"
      - "tests/**"
      - "functions/.zsh-eza"
      - "zsh-eza.plugin.zsh"
  pull_request:
    branches: [next, main]
    paths:
      - ".github/workflows/test-native.yml"
      - "tests/**"
      - "functions/.zsh-eza"
      - "zsh-eza.plugin.zsh"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zunit:
    name: "ZUnit: zsh-eza"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Zsh
        uses: z-shell/.github/actions/setup-zsh@8ee041623cd5a2892887357ea9f0fb443ff3d2b4 # main
      - name: Install git and curl
        run: sudo apt-get update && sudo apt-get install -yq git curl
      - name: Make vendored bin executable
        run: chmod u+x bin/{color,revolver,zunit}
      - name: Run ZUnit suite
        run: |
          export PATH="$PWD/bin:$PATH"
          export ZSH_EZA_REPO="$PWD"
          zunit --tap --verbose tests/zsh-eza.zunit
