---
name: Zsh Syntax Check

on:
  push:
    branches: [next, main]
    paths:
      - "*.zsh"
      - "functions/.*"
  pull_request:
    branches: [next, main]
    paths:
      - "*.zsh"
      - "functions/.*"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zsh-n:
    name: Zsh Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
      - name: Set up Zsh
        uses: z-shell/.github/actions/setup-zsh@2f42fb3d8d74582aa9dd99c884eda45078d95579 # main
      - name: Check Zsh syntax
        run: |
          find . -type f \( -name '*.zsh' -o -path './functions/.*' \) -print | sort | while read -r file; do
            zsh -n "$file"
            zsh -fc 'zcompile -- "$1"' zsh "$file"
            rm -f "${file}.zwc"
          done
