---
name: Zsh Lint

on:
  push:
    branches: [next, main]
    paths:
      - "zsh-eza.plugin.zsh"
      - ".github/workflows/zsh-lint.yml"
  pull_request:
    branches: [next, main]
    paths:
      - "zsh-eza.plugin.zsh"
      - ".github/workflows/zsh-lint.yml"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zsh-lint:
    name: Zsh Lint
    uses: z-shell/.github/.github/workflows/zsh-lint.yml@1b790f9ac271fbec149f8c92cd9c4fb2e59cc6ac # zsh-lint/v1.0.0
    with:
      zsh-lint-ref: 3c4966b454fc07a346772a24d8311adab91414ed
      paths: |
        zsh-eza.plugin.zsh
