---
name: Zsh Syntax Check

on:
  push:
    branches: [next, main]
    paths:
      - "*.zsh"
      - "functions/.*"
  pull_request:
    branches: [next, main]
    paths:
      - "*.zsh"
      - "functions/.*"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zsh-n:
    name: Zsh Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Zsh
        uses: z-shell/.github/actions/setup-zsh@934a11240ae176a36a72da4a7a495ab2f1eabbb3 # main
      - name: Check Zsh syntax
        run: |
          find . -type f \( -name '*.zsh' -o -path './functions/.*' \) -print | sort | while read -r file; do
            zsh -n "$file"
            zsh -fc 'zcompile -- "$1"' zsh "$file"
            rm -f "${file}.zwc"
          done
